# Generated by Django 3.1.4 on 2021-02-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210210_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='Product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pub_date',
            new_name='Pub_date',
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
